[package]
name = "terminal-fireworks"
version = "1.0.0"
edition = "2021"
description = "A terminal based fireworks display"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
